[package]
name = "res"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
eframe = "0.28.1"
egui-file-dialog = "0.6.0"
egui_extras = "0.28.1"
open = "5.3.2"
regex = "1.10.6"
walkdir = "2.5.0"
